### ISSUE TITLE
Finish up implementing adjacency list based graph class

### ISSUE THREAD

**Issue by handlessdude** [mmcs-ruby/visual_graphs#4]
Make sure class include:
- [x] initialization by json import
- [ ] initialization by taking adjacency list as parameter (in hash presentation)
- [x] vertices array getter
- [x] edges array getter
- [ ] inserting a new vertex to existing graph
- [ ] inserting a new edge to existing graph
- [ ] output to standard output stream (useful for graph mutation debug)
- [ ] output to json file (useful for graph mutation debug)
- [ ] necessary tests 
- [ ] necessary docs

**Comment by selfmadekirich** [comment]
take it
